#include<bits/stdc++.h>
using namespace std;
int main()
{
    string a1,b1,c1;
    int i,a=0,b=0,c=0,d=0,e=0,f=0,g=0,h=0,I=0,j=0,k=0,l=0,m=0,n=0,o=0,p=0,q=0,r=0,s=0,t=0,u=0,v=0,w=0,x=0,y=0,z=0,a2=0,b2=0,c2=0,d2=0,e2=0,f2=0,g2=0,h2=0,i2=0,j2=0,k2=0,l2=0,m2=0,n2=0,o2=0,p2=0,q2=0,r2=0,s2=0,t2=0,u2=0,v2=0,w2=0,x2=0,y2=0,z2=0;
    cin>>a1;
    cin>>b1;
    cin>>c1;
    for(i=0;a1[i]!='\0';i++)
    {
        if(a1[i]=='A')
        a++;
                if(a1[i]=='B')
        b++;
          if(a1[i]=='C')
        c++;
                if(a1[i]=='D')
        d++;
                if(a1[i]=='E')
        e++;
                if(a1[i]=='F')
        f++;
          if(a1[i]=='G')
        g++;
                if(a1[i]=='H')
        h++;
                if(a1[i]=='I')
        I++;
                if(a1[i]=='J')
        j++;
          if(a1[i]=='K')
        k++;
                if(a1[i]=='L')
        l++;
                if(a1[i]=='M')
        m++;
                if(a1[i]=='N')
        n++;
          if(a1[i]=='O')
        o++;
                if(a1[i]=='P')
        p++;
           if(a1[i]=='Q')
        q++;
                if(a1[i]=='R')
        r++;
                if(a1[i]=='S')
        s++;
                if(a1[i]=='T')
        t++;
          if(a1[i]=='U')
        u++;
                if(a1[i]=='V')
        v++;
                if(a1[i]=='W')
        w++;
                if(a1[i]=='X')
        x++;
          if(a1[i]=='Y')
        y++;
                if(a1[i]=='Z')
        z++;


    }
        for(i=0;b1[i]!='\0';i++)
    {
        if(b1[i]=='A')
        a++;
                if(b1[i]=='B')
        b++;
          if(b1[i]=='C')
        c++;
                if(b1[i]=='D')
        d++;
                if(b1[i]=='E')
        e++;
                if(b1[i]=='F')
        f++;
          if(b1[i]=='G')
        g++;
                if(b1[i]=='H')
        h++;
                if(b1[i]=='I')
        I++;
                if(b1[i]=='J')
        j++;
          if(b1[i]=='K')
        k++;
                if(b1[i]=='L')
        l++;
                if(b1[i]=='M')
        m++;
                if(b1[i]=='N')
        n++;
          if(b1[i]=='O')
        o++;
                if(b1[i]=='P')
        p++;
           if(b1[i]=='Q')
        q++;
                if(b1[i]=='R')
        r++;
                if(b1[i]=='S')
        s++;
                if(b1[i]=='T')
        t++;
          if(b1[i]=='U')
        u++;
                if(b1[i]=='V')
        v++;
                if(b1[i]=='W')
        w++;
                if(b1[i]=='X')
        x++;
          if(b1[i]=='Y')
        y++;
                if(b1[i]=='Z')
        z++;


    }
        for(i=0;c1[i]!='\0';i++)
    {
        if(c1[i]=='A')
        a2++;
                if(c1[i]=='B')
        b2++;
          if(c1[i]=='C')
        c2++;
                if(c1[i]=='D')
        d2++;
                if(c1[i]=='E')
        e2++;
                if(c1[i]=='F')
        f2++;
          if(c1[i]=='G')
        g2++;
                if(c1[i]=='H')
        h2++;
                if(c1[i]=='I')
        i2++;
                if(c1[i]=='J')
        j2++;
          if(c1[i]=='K')
        k2++;
                if(c1[i]=='L')
        l2++;
                if(c1[i]=='M')
        m2++;
                if(c1[i]=='N')
        n2++;
          if(c1[i]=='O')
        o2++;
                if(c1[i]=='P')
        p2++;
           if(c1[i]=='Q')
        q2++;
                if(c1[i]=='R')
        r2++;
                if(c1[i]=='S')
        s2++;
                if(c1[i]=='T')
        t2++;
          if(c1[i]=='U')
        u2++;
                if(c1[i]=='V')
        v2++;
                if(c1[i]=='W')
        w2++;
                if(c1[i]=='X')
        x2++;
          if(c1[i]=='Y')
        y2++;
                if(c1[i]=='Z')
        z2++;


    }
    if((a==a2) &&(b==b2) && (c==c2) && (d==d2) && (e==e2) && (f==f2) && (g==g2) && (h==h2) && (I==i2) && (j==j2) && (k==k2) && (l==l2) &&(m==m2) && (n==n2) &&(o==o2) && (q==q2) && (r==r2) && (s==s2) && (t==t2) && (p==p2) && (u==u2) && (v==v2) && (w==w2) && (x==x2) && (y==y2) && (z==z2) )
  cout<<"YES";
  else
    cout<<"NO";


   //cout<<a<< b<< c<< d<<  e<< f<< g<< h<< I<<  j<<  k<<  l<<  m << n<< o << p<< q<< r<< s<< t << u<< v<< w<< x<< y<< z<<endl<<a2<<b2<<c2<<d2<<e2<<f2<<g2<<h2<<i2<<j2<<k2<<l2<<m2<<n2<<o2<<p2<<q2<<r2<<s2<<u2<<v2<<w2<<x2<<y2<<z2;

}
